### ISSUE TITLE
Strange warning accussing any mimetype of not being an image. 

### ISSUE THREAD

**Issue by gusbemacbe** [bjorno43/ImageSecure#10]
The result is:

```
File: produto-01.jpeg is not an image. The file is removed!
Your images can be viewed here:
```

In the config file:

```ini
define("R_PATH", __DIR__);
define("F_PATH", R_PATH.'/assets/imagens/produtos');
define("H_FILE", true);
```

In the file `imgupload.class`:

```php
    private function check_img_mime($tmpname)
    {
        $finfo       = finfo_open(FILEINFO_MIME_TYPE);
        $mtype       = finfo_file($finfo, $tmpname);
        $this->mtype = $mtype;

        if (strpos($mtype, '/assets/imagens/produtos/') === 0)
        {
            return true;
        }

        return false;

        finfo_close($finfo);
    }
```

The database:

![imagem](https://user-images.githubusercontent.com/2257024/111070177-1f0cae00-84af-11eb-9efd-1bb219bcb0c4.png)

[Envio, Substituição e Actualização.zip](https://github.com/bjorno43/ImageSecure/files/6136740/Envio.Substituicao.e.Actualizacao.zip)

**Comment by bjorno43** [comment]
This is not an issue, but an error on your own side. You've changed `if(strpos($mtype, 'image/') === 0){` to `if (strpos($mtype, '/assets/imagens/produtos/') === 0)`, which doesn't work. That line is not a directory line. It's a MIME type. You should NEVER change it.
