### ISSUE TITLE
Possible missing fileinfo closing

### ISSUE THREAD

**Issue by WesleyGoncalves** [bjorno43/ImageSecure#5]
In the method `ImageUpload::check_img_mime()` the closing of the fileinfo  is after the `return` statements. 
I believe it should be before the `if` statement of this method so that the fileinfo resource is effectively closed.

**Comment by amin007** [comment]
function on class ImageUpload to dificult do understand

**Comment by bjorno43** [comment]
There were some issues with the code uploaded to Github. The correct code is now there. I expect the issues to be solved. If there are still more problems, please let me know.
