### ISSUE TITLE
Warning on upload. Still works but the warning shows.

### ISSUE THREAD

**Issue by LachieKimber** [bjorno43/ImageSecure#6]
Warning: Creating default object from empty value in imgupload.class.php on line 292

**Comment by amin007** [comment]
i get some warning to0. function on class ImageUpload to dificult do understand

**Comment by bjorno43** [comment]
There are some problems with the code on Github itself. I have been away from this for a very long time. I will apply the correct code to Github soon which should fix those problems.

**Comment by bjorno43** [comment]
All the correct code is now applied. If there are still any issues, please let me know.
