### ISSUE TITLE
Need to resize image to fit in 350x350 box

### ISSUE THREAD

**Issue by NJseo** [bjorno43/ImageSecure#7]
Your library was easy to setup, though I did expect to see more on the read me, but what has me puzzled is how I take advantage of GD resizing. The images can be far too big from the user. I tried adding a GD function to resize but I am getting grief with that. Can you help or add a resize feature to the script?

**Comment by bjorno43** [comment]
This library was never meant to be used for resizing images. It's only meant to be used to securely handle images uploaded by your users. If you set it up correctly, users will get an error message if they try to upload anything you consider "too large".

If you just want to resize the width and / or height properties, use a simple `<img>` element with the src attribute set to `image.php?id=##`. After that you can use CSS to style the element as usual.
